# Generated by Django 3.2.5 on 2021-10-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='request_flag',
            field=models.BooleanField(null=True),
        ),
    ]
